-- Table: REFUGES
CREATE TABLE REFUGES (
    EMAILREF          VARCHAR2(50)  NOT NULL PRIMARY KEY,
    NOMREF            VARCHAR2(50)  NOT NULL,
    SECTEURGEO        VARCHAR2(50)  NOT NULL,
    DATE_OUVERTURE    DATE          NOT NULL,
    DATE_FERMETURE    DATE          NOT NULL,
    NB_PLACES_REPAS   NUMBER        NOT NULL CHECK (NB_PLACES_REPAS > 0),
    NB_PLACES_DORMIR  NUMBER        NOT NULL CHECK (NB_PLACES_DORMIR > 0),
    PRIX_NUIT         NUMBER        NOT NULL CHECK (PRIX_NUIT > 0),
    TEXT_PRESENTATION VARCHAR2(500) NOT NULL,
    CHECK (DATE_OUVERTURE < DATE_FERMETURE)
);

-- Table: TELEPHONE
CREATE TABLE TELEPHONE (
    NUM_TEL  VARCHAR2(10) NOT NULL PRIMARY KEY,
    EMAILREF VARCHAR2(50) NOT NULL REFERENCES REFUGES
);

-- Table: UTILISATEUR
CREATE TABLE UTILISATEUR (
    IDMEMBRE NUMBER NOT NULL PRIMARY KEY
);

-- Table: MEMBRE
CREATE TABLE MEMBRE (
    ADR_EMAIL    VARCHAR2(50) NOT NULL,
    IDMEMBRE     NUMBER      NOT NULL REFERENCES UTILISATEUR PRIMARY KEY,
    NOM          VARCHAR2(50) NOT NULL,
    PRENOM       VARCHAR2(50) NOT NULL,
    ADR_POSTALE  VARCHAR2(50) NOT NULL,
    SOMME_DUE    NUMBER      NOT NULL CHECK (SOMME_DUE >= 0),
    SOMME_REGLEE NUMBER      NOT NULL CHECK (SOMME_REGLEE >= 0),
    MOT_DE_PASSE VARCHAR2(50) NOT NULL,
    CHECK (SOMME_REGLEE <= SOMME_DUE)
);

-- Table: RESERVEREFUGE
CREATE TABLE RESERVEREFUGE (
    IDMEMBRE  NUMBER       NOT NULL REFERENCES UTILISATEUR,
    IDRES     NUMBER       NOT NULL PRIMARY KEY,
    DATE_RES  DATE         NOT NULL,
    HEURE_RES VARCHAR2(20) NOT NULL,
    NB_NUITS  NUMBER       NOT NULL CHECK (NB_NUITS >= 0),
    NB_REPAS  NUMBER       NOT NULL CHECK (NB_REPAS >= 0),
    PRIX_RES  NUMBER       NOT NULL CHECK (PRIX_RES >= 0),
    EMAILREF  VARCHAR2(50) NOT NULL REFERENCES REFUGES
);


-- Table: ADHERENT
CREATE TABLE ADHERENT (
    IDADHERENT NUMBER NOT NULL PRIMARY KEY,
    IDMEMBRE   NUMBER NOT NULL REFERENCES UTILISATEUR
);

-- Table: FORMATION
CREATE TABLE FORMATION (
    IDFORM         NUMBER        NOT NULL,
    ANNEEFORM      NUMBER        NOT NULL,
    NOMFORM        VARCHAR2(50)  NOT NULL,
    DATE_DEBUT     DATE          NOT NULL,
    DUREE          NUMBER        NOT NULL CHECK (DUREE > 0),
    NBPLACES       NUMBER        NOT NULL CHECK (NBPLACES > 0),
    UNEDESCRIPTION VARCHAR2(500) NOT NULL,
    PRIX           NUMBER        NOT NULL CHECK (PRIX > 0),
    PRIMARY KEY (IDFORM, ANNEEFORM)
);

-- Table: RESERVEFORMATION
CREATE TABLE RESERVEFORMATION (
    IDRES      NUMBER NOT NULL PRIMARY KEY,
    IDADHERENT NUMBER NOT NULL REFERENCES ADHERENT,
    IDFORM     NUMBER NOT NULL,
    ANNEEFORM  NUMBER NOT NULL,
    FOREIGN KEY (IDFORM, ANNEEFORM) REFERENCES FORMATION
);

-- Table: FORMATIONATTENTE
CREATE TABLE FORMATIONATTENTE (
    IDRES       NUMBER NOT NULL PRIMARY KEY REFERENCES RESERVEFORMATION,
    RANGATTENTE NUMBER NOT NULL CHECK (RANGATTENTE > 0)
);

-- Table: ACTIVITE
CREATE TABLE ACTIVITE (
    NOMACT VARCHAR2(50) NOT NULL PRIMARY KEY
);

-- Table: MATCAT
CREATE TABLE MATCAT (
    CATEGORIE VARCHAR2(50) NOT NULL PRIMARY KEY
);

-- Table: LOTMATERIEL
CREATE TABLE LOTMATERIEL (
    MARQUE    VARCHAR2(50) NOT NULL,
    MODELE    VARCHAR2(50) NOT NULL,
    ANNEE     NUMBER       NOT NULL,
    NBPIECES  NUMBER       NOT NULL CHECK (NBPIECES > 0),
    PRIXDEG   NUMBER       NOT NULL CHECK (PRIXDEG >= 0),
    CATEGORIE VARCHAR2(50) NOT NULL REFERENCES MATCAT,
    PRIMARY KEY (MARQUE, MODELE, ANNEE)
);

-- Table: LOCATIONS
CREATE TABLE LOCATIONS (
    IDLOC           NUMBER       NOT NULL PRIMARY KEY,
    NBPIECES        NUMBER       NOT NULL CHECK (NBPIECES > 0),
    DATERECUP       DATE         NOT NULL,
    DATERETOUR      DATE         NOT NULL,
    NBPIECESPERDUES NUMBER       NOT NULL CHECK (NBPIECESPERDUES >= 0),
    MARQUE          VARCHAR2(50) NOT NULL,
    MODELE          VARCHAR2(50) NOT NULL,
    ANNEE           NUMBER       NOT NULL,
    IDADHERENT      NUMBER       NOT NULL REFERENCES ADHERENT,
    FOREIGN KEY (MARQUE, MODELE, ANNEE) REFERENCES LOTMATERIEL,
    CHECK (DATERETOUR <= DATERECUP + 14),
    CHECK (NBPIECESPERDUES <= NBPIECES)
);

-- Table: INFOMATERIEL
CREATE TABLE INFOMATERIEL (
    INFO   VARCHAR2(50) NOT NULL PRIMARY KEY,
    MARQUE VARCHAR2(50) NOT NULL,
    MODELE VARCHAR2(50) NOT NULL,
    ANNEE  NUMBER       NOT NULL,
    FOREIGN KEY (MARQUE, MODELE, ANNEE) REFERENCES LOTMATERIEL
);

-- Table: MATERIELPERISSABLE
CREATE TABLE MATERIELPERISSABLE (
    MARQUE         VARCHAR2(50) NOT NULL,
    MODELE         VARCHAR2(50) NOT NULL,
    ANNEE          NUMBER       NOT NULL,
    DATEPEREMPTION DATE         NOT NULL,
    PRIMARY KEY (MARQUE, MODELE, ANNEE),
    FOREIGN KEY (MARQUE, MODELE, ANNEE) REFERENCES LOTMATERIEL
);

-- Table: MATERIELACTIVITE
CREATE TABLE MATERIELACTIVITE (
    NOMACT VARCHAR2(50) NOT NULL REFERENCES ACTIVITE,
    MARQUE VARCHAR2(50) NOT NULL,
    MODELE VARCHAR2(50) NOT NULL,
    ANNEE  NUMBER       NOT NULL CHECK (ANNEE > 2023),
    PRIMARY KEY (NOMACT, MARQUE, MODELE, ANNEE),
    FOREIGN KEY (MARQUE, MODELE, ANNEE) REFERENCES LOTMATERIEL
);

-- Table: PAIEMENT
CREATE TABLE PAIEMENT (
    TYPE_PAIEMENT VARCHAR2(50) NOT NULL PRIMARY KEY CHECK (TYPE_PAIEMENT IN ('CB', 'Chèque', 'Espèces'))
);

-- Table: REFUGE_PAIEMENT
CREATE TABLE REFUGE_PAIEMENT (
    TYPE_PAIEMENT VARCHAR2(50) NOT NULL REFERENCES PAIEMENT CHECK (TYPE_PAIEMENT IN ('CB', 'Chèque', 'Espèces')),
    EMAILREF      VARCHAR2(50) NOT NULL REFERENCES REFUGES,
    PRIMARY KEY (TYPE_PAIEMENT, EMAILREF)
);

-- Table: REPAS
CREATE TABLE REPAS (
    NOM_REPAS VARCHAR2(80) NOT NULL PRIMARY KEY CHECK (NOM_REPAS IN ('déjeuner', 'dîner', 'souper', 'casse-croûte à emporter'))
);

-- Table: PROPOSEREPAS
CREATE TABLE PROPOSEREPAS (
    EMAILREF   VARCHAR2(50) NOT NULL REFERENCES REFUGES,
    NOM_REPAS  VARCHAR2(50) NOT NULL REFERENCES REPAS,
    PRIX_REPAS NUMBER       NOT NULL CHECK (PRIX_REPAS > 0),
    PRIMARY KEY (EMAILREF, NOM_REPAS)
);

-- Table: FORMATIONACTIVITE
CREATE TABLE FORMATIONACTIVITE (
    NOMACT    VARCHAR2(50) NOT NULL REFERENCES ACTIVITE,
    ANNEEFORM NUMBER       NOT NULL,
    IDFORM    NUMBER       NOT NULL,
    PRIMARY KEY (NOMACT, ANNEEFORM, IDFORM),
    FOREIGN KEY (IDFORM, ANNEEFORM) REFERENCES FORMATION
);

-- Table: MATUTILACTIV
CREATE TABLE MATUTILACTIV (
    NOMACT VARCHAR2(50) NOT NULL REFERENCES ACTIVITE,
    MARQUE VARCHAR2(50) NOT NULL,
    MODELE VARCHAR2(50) NOT NULL,
    ANNEE  NUMBER       NOT NULL,
    PRIMARY KEY (NOMACT, MARQUE, MODELE, ANNEE),
    FOREIGN KEY (MARQUE, MODELE, ANNEE) REFERENCES LOTMATERIEL
);

-- Table: CATEGORIEMERE
CREATE TABLE CATEGORIEMERE (
    SOUSCATEGORIE VARCHAR2(100) NOT NULL PRIMARY KEY,
    CATEGORIEMERE VARCHAR2(100) NOT NULL
);



